### ISSUE TITLE
Predicting own sentences

### ISSUE THREAD

**Issue by gifflarn** [dongjun-Lee/text-summarization-tensorflow#4]
How does one supply own sentences to this model to get summarized?
As far as I am seeing, the prediction uses the title as well as the sentence in the test set to create a new sentence. Is there any way to bypass the usage of titles and just feed sentences?

**Comment by dongjun-Lee** [comment]
Hi, titles are only used for training. Titles are not used for prediction. As you can see at [here](https://github.com/dongjun-Lee/text-summarization-tensorflow/blob/master/utils.py#L68-L70), only X(original sentences) are used for prediction.
To test the model with your own data, you might need to change [here](https://github.com/dongjun-Lee/text-summarization-tensorflow/blob/master/utils.py#L68-L70) to load your own data.

**Comment by SundareshPrasanna** [comment]
Hi Lee, 
If i were to modify this code for testing so that it only expects articles for testing, how should i modify the code to incorporate the change? I tried changing the 2 functions, build_dataset() & batch_iter in utils.py for testing as below:

`def build_dataset_test(step, word_dict, article_max_len, summary_max_len, toy=False):
    if step == "valid":
        article_list = get_text_list(valid_article_path, toy)
        #title_list = get_text_list(valid_title_path, toy)
    else:
        raise NotImplementedError
    x = list(map(lambda d: word_tokenize(d), article_list))
    x = list(map(lambda d: list(map(lambda w: word_dict.get(w, word_dict["<unk>"]), d)), x))
    x = list(map(lambda d: d[:article_max_len], x))
    x = list(map(lambda d: d + (article_max_len - len(d)) * [word_dict["<padding>"]], x))
    return x` 
`def batch_iter2(inputs, batch_size, num_epochs):
    inputs = np.array(inputs)
    #outputs = np.array(outputs)

    num_batches_per_epoch = (len(inputs) - 1) // batch_size + 1
    for epoch in range(num_epochs):
        for batch_num in range(num_batches_per_epoch):
            start_index = batch_num * batch_size
            end_index = min((batch_num + 1) * batch_size, len(inputs))
            yield inputs[start_index:end_index]`

I called these fns in test.py & modified the code accordingly by changing lines below:
`valid_x = build_dataset_test("valid", word_dict, article_max_len, summary_max_len, args.toy)`
`batches = batch_iter2(valid_x, args.batch_size, 1)`
`for batch_x in batches:`

on doing so i am getting a KeyError: -1 as output. What else should i change to consider only the articles & not the title (even tho title is not used for prediction purpose)

**Comment by dongjun-Lee** [comment]
@SundareshPrasanna Hi. Sorry for the late reply. I'll fix the code soon so that you can easily test your own data.

**Comment by dongjun-Lee** [comment]
@SundareshPrasanna Would [this commit](2721381ab53796d52b0330d9911491294fadbfd9) helps you?
